Repository EuroguessrTeam/Euroguessr, pull requests merged in 2023-11, with the labels that each got.

#42 Fix/broken docker
  Dockerfile
  docker-compose.local.yaml
  docker-compose.yaml
Labels: bug, continuous deployment

#44 Update develop
  Euroguessr.Data/SongsData.json
  Euroguessr/Controllers/HomeController.cs
  Euroguessr/Models/Pages/Index/IndexModel.cs
  Euroguessr/Models/Pages/Training/TrainingModel.cs
  Euroguessr/Views/Home/Training.cshtml
  Euroguessr/Views/Shared/_Layout.cshtml
  Euroguessr/wwwroot/css/pages/training/training.css
  Euroguessr/wwwroot/js/pages/training/buttonsActions.js
  Euroguessr/wwwroot/js/pages/training/training.js
Labels: front-end

#37 36 documentation to run the program locally
  README.md
  docs/ProjectSetup.md
Labels: documentation

#61 59 development setup
  docs/Project setup with docker.md
  docs/Project setup.md
Labels: documentation

#63 51 fix the send button not showing bug on firefox
  Euroguessr/Views/Home/Index copy.cshtml
  Euroguessr/Views/Home/Index.cshtml
  Euroguessr/wwwroot/css/index.css
  Euroguessr/wwwroot/css/pages/training/training.css
  Euroguessr/wwwroot/css/projector.css
  Euroguessr/wwwroot/js/index.js
  Euroguessr/wwwroot/js/pages/training/buttonsActions.js
  Euroguessr/wwwroot/js/pages/training/training.js
  Euroguessr/wwwroot/js/projector.js
Labels: bug, front-end

#65 feat(LazyLoadIMG): add a lazy load to all image who habe a data-src a…
  Euroguessr/Views/Home/Index.cshtml
  Euroguessr/Views/Home/Training.cshtml
  Euroguessr/wwwroot/js/lazyLoadImages.js
Labels: front-end

#69 #68 Create API for React (broken front end)
  Euroguessr.Data/Euroguessr.Data.csproj
  Euroguessr.Data/Interfaces/ISongManagerService.cs
  Euroguessr.Data/Services/AccountManagerService.cs
  Euroguessr.Data/Tables/Score.cs
  Euroguessr.Data/Tables/Song.cs
  Euroguessr.Data/Tables/User.cs
  Euroguessr/Controllers/HomeController.cs
  Euroguessr/Controllers/SongController.cs
  Euroguessr/Controllers/UserController.cs
  Euroguessr/Euroguessr.csproj
  Euroguessr/Managers/ActionButtonsManager.cs
  Euroguessr/Managers/FormManager.cs
  Euroguessr/Models/Api/Song/Input/InputSubmitSongModel.cs
  Euroguessr/Models/Api/Song/Output/OutputGetDailySongModel.cs
  Euroguessr/Models/Api/Song/Output/OutputSubmitSong.cs
  Euroguessr/Models/Api/User/Input/InputRestoreAccountModel.cs
  Euroguessr/Models/Api/User/Output/OutputGetUserIdModel.cs
  Euroguessr/Models/Api/User/Output/OutputRestoreAccountModel.cs
  Euroguessr/Program.cs
  Euroguessr/Services/SongToGuessService.cs
  README.md
  docs/File-structure-react.md
  docs/Project-setup-with-docker.md
  docs/Project-setup.md
  euroguessr-front/.eslintrc.cjs
  euroguessr-front/.gitignore
  euroguessr-front/README.md
  euroguessr-front/index.html
  euroguessr-front/package-lock.json
  euroguessr-front/package.json
  euroguessr-front/postcss.config.js
  euroguessr-front/public/favicon.ico
  euroguessr-front/public/fonts/open-sans/regular.ttf
  euroguessr-front/src/assets/images/icons/favicon.png
  euroguessr-front/src/components/header/Header.tsx
  euroguessr-front/src/components/header/Link.tsx
  euroguessr-front/src/config/routes.tsx
  euroguessr-front/src/layout/Root.tsx
  euroguessr-front/src/main.tsx
  euroguessr-front/src/pages/Daily.tsx
  euroguessr-front/src/pages/Privacy.tsx
  euroguessr-front/src/styles/index.css
  euroguessr-front/src/utils/debounce.ts
  euroguessr-front/src/vite-env.d.ts
  euroguessr-front/tailwind.config.js
  euroguessr-front/tsconfig.json
  euroguessr-front/tsconfig.node.json
  euroguessr-front/vite.config.ts
Labels: back-end

#70 Change version of .NET in develop. .NET 6 -> .NET 8
  Dockerfile
  Euroguessr/Euroguessr.csproj
  euroguessr-front/package-lock.json
  euroguessr-front/package.json
  euroguessr-front/postcss.config.js
  euroguessr-front/src/components/header/Header.tsx
  euroguessr-front/src/components/header/Link.tsx
  euroguessr-front/src/config/routes.tsx
  euroguessr-front/src/main.tsx
  euroguessr-front/src/pages/Daily.tsx
  euroguessr-front/src/pages/Help.tsx
  euroguessr-front/src/pages/Privacy.tsx
  euroguessr-front/src/styles/header/header.scss
  euroguessr-front/src/styles/help/help.scss
  euroguessr-front/src/styles/index.css
  euroguessr-front/src/styles/index.scss
  euroguessr-front/src/styles/privacy/privacy.scss
  euroguessr-front/src/styles/variables.scss
  euroguessr-front/src/utils/debounce.ts
  euroguessr-front/tailwind.config.js
Labels: back-end, infra

#71 README.md issues fixed
  README.md
Labels: bug, documentation

#72 README.md issues fixed
  README.md
Labels: bug, documentation

#73 Update README.md
  README.md
Labels: documentation
