Repository EuroguessrTeam/Euroguessr, pull requests merged in 2023-10, with the labels that each got.

#4 2 rédaction readme
  README.md
Labels: documentation

#5 Develop
  README.md
Labels: documentation

#8 Merge conf docker into develop
  .env.example
  .gitignore
  Euroguessr/Program.cs
  docker-compose.yaml
Labels: continuous deployment

#21 Cool transition for the home page created + fix the infinite loading …
  Euroguessr/Views/Home/Index.cshtml
  Euroguessr/Views/Shared/_Layout.cshtml.css
  Euroguessr/wwwroot/css/Index.css
  Euroguessr/wwwroot/js/Index.js
Labels: bug, front-end

#22 Issue #19 done + fix infinite loading song bug
  Euroguessr/Views/Home/Index.cshtml
  Euroguessr/Views/Shared/_Layout.cshtml.css
  Euroguessr/wwwroot/css/Index.css
  Euroguessr/wwwroot/js/Index.js
Labels: bug, front-end

#20 feat: Add github action to build and publish docker image
  .github/workflows/build-publish-docker.yaml
Labels: back-end

#23 feat: add https support
  .gitignore
  docker-compose.yaml
Labels: back-end

#24 Develop to master (add https support + Add github action to build and publish docker image)
  .github/workflows/build-publish-docker.yaml
  .gitignore
  docker-compose.yaml
Labels: back-end

#25 Update readme.md
  README.md
Labels: documentation

#26 Update readme.md
  README.md
Labels: documentation

#28 Help and Privacy page filled
  Euroguessr/Views/Home/Help.cshtml
  Euroguessr/Views/Home/Privacy.cshtml
Labels: enhancement, front-end

#29 Privacy and Help page done
  Euroguessr/Views/Home/Help.cshtml
  Euroguessr/Views/Home/Privacy.cshtml
Labels: enhancement, front-end
